spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

  management:
    endpoints:
      web:
        exposure:
          include: health, refresh

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/rootsandgo-realm"

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /swagger-config
    oauth:
      client-id: rootsandgo-client
      use-basic-authentication-with-access-code-grant: true
    persistAuthorization: true
