server:
  port: 8081

# dev config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5434/db_business
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

aws:
  s3:
    access: ${access}
    secret: ${secret}
    region: eu-north-1
    bucket: roots-business
---
# test config
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  # Désactiver la sécurité pour les tests
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://test-disabled"

aws:
  s3:
    mock: true
    access: test-access
    secret: test-secret
    region: test-region
    bucket: test-bucket

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.SQL: DEBUG


