spring:
  management:
    observations:
      key-values:
        application: gateway-service
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: lb://BUSINESS-SERVICE
            predicates:
              - Path=/business-service/**
          - id: r2
            uri: lb://GP-SERVICE
            predicates:
              - Path=/gp-service/**
          - id: r3
            uri: lb://ECOM-SERVICE
            predicates:
              - Path=/ecom-service/**
          - id: r4
            uri: lb://IMMO-SERVICE
            predicates:
              - Path=/immo-service/**
          - id: r5
            uri: lb://PROFILE-SERVICE
            predicates:
              - Path=/profile-service/**
          - id: r6
            uri: lb://RESTAURANT-SERVICE
            predicates:
              - Path=/restaurant-service/**

springdoc:
  swagger-ui:
    url: /swagger-config
    path: /swagger-ui.html
