server:
  port: 8088

spring:
  management:
    observations:
      key-values:
        application: gateway-service
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      mvc:
        routes:
          - id: r1
            uri: lb://BUSINESS-SERVICE
            predicates:
              - Path=/business-service/**
          - id: r2
            uri: lb://GP-SERVICE
            predicates:
              - Path=/gp-service/**
          - id: r3
            uri: lb://ECOM-SERVICE
            predicates:
              - Path=/ecom-service/**
          - id: r4
            uri: lb://IMMO-SERVICE
            predicates:
              - Path=/immo-service/**
springdoc:
  swagger-ui:
    url: /swagger-config
    path: /swagger-ui.html
